# Generated by Django 3.2.6 on 2021-08-03 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_id', models.EmailField(max_length=254, unique=True, verbose_name='email_id')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('nickname', models.CharField(max_length=30, verbose_name='nickname')),
                ('phonenum', models.CharField(max_length=30, verbose_name='phonenum')),
                ('gender', models.CharField(choices=[('MALE', '남성(Man)'), ('FEMALE', '여성(Woman)')], max_length=30, verbose_name='gender')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
