# Generated by Django 3.2.6 on 2021-08-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
    ]
