# Generated by Django 3.2.6 on 2021-08-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자'},
        ),
    ]
