# Generated by Django 3.2.6 on 2021-08-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='dibs',
        ),
    ]
