# Generated by Django 3.2.6 on 2021-08-04 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dib',
            name='users',
            field=models.ManyToManyField(related_name='requirement_service_dibs', to=settings.AUTH_USER_MODEL),
        ),
    ]
