# Generated by Django 3.2.6 on 2021-08-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_dib_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dib',
        ),
    ]
