<<<<<<< Updated upstream
# Generated by Django 3.2.6 on 2021-08-20 13:41
=======
# Generated by Django 3.2.6 on 2021-08-20 13:31
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_magazine_category'),
=======
        ('community', '0002_magazine_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL),
        ),
    ]
