<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-19 09:23
=======
# Generated by Django 3.2.6 on 2021-08-19 16:46
>>>>>>> a7e898fecc934afda6c7e3c57a1f721c1c03d99f

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_magazine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL),
        ),
    ]
