<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-12 11:22
=======
# Generated by Django 3.2.6 on 2021-08-12 01:49
>>>>>>> 2f0b80a5dd0c5ecd966b3f3ae09e3f0752a79281

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('reviews', '0001_initial'),
        ('likes', '0001_initial'),
=======
        ('likes', '0001_initial'),
        ('reviews', '0001_initial'),
>>>>>>> 2f0b80a5dd0c5ecd966b3f3ae09e3f0752a79281
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='review',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_help', to='reviews.review'),
        ),
    ]
