<<<<<<< HEAD:likes/migrations/0002_initial.py
# Generated by Django 3.2.6 on 2021-08-10 06:32
=======
# Generated by Django 3.2.6 on 2021-08-10 07:29
>>>>>>> service_list:likes/migrations/0002_help_review.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:likes/migrations/0002_initial.py
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
        ('reviews', '0001_initial'),
=======
        ('reviews', '0001_initial'),
        ('likes', '0001_initial'),
>>>>>>> service_list:likes/migrations/0002_help_review.py
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='review',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_help', to='reviews.review'),
        ),
    ]
