# Generated by Django 3.2.6 on 2021-08-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dib',
        ),
    ]
