# Generated by Django 3.2.6 on 2021-08-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('likes', '0003_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='review',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
