# Generated by Django 3.2.6 on 2021-08-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_target'),
        ('likes', '0004_alter_help_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='review',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_help', to='reviews.review'),
        ),
    ]
