# Generated by Django 3.2.6 on 2021-08-14 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        << << << < HEAD
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        == == == =
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
        >>>>>> > d25679b2aac020b3b010316a9cb240f3da4680d8
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
