<<<<<<< HEAD:reviews/migrations/0002_review_user.py
# Generated by Django 3.2.6 on 2021-08-13 23:06
=======
# Generated by Django 3.2.6 on 2021-08-12 02:38
>>>>>>> userlogin:reviews/migrations/0003_review_user.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD:reviews/migrations/0002_review_user.py
        ('reviews', '0001_initial'),
=======
        ('reviews', '0002_review_target'),
>>>>>>> userlogin:reviews/migrations/0003_review_user.py
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
