<<<<<<< HEAD:reviews/migrations/0003_review_user.py
# Generated by Django 3.2.6 on 2021-08-09 07:29
=======
# Generated by Django 3.2.6 on 2021-08-08 11:58
>>>>>>> a290a77db247e240a0718b80735afd3911709973:reviews/migrations/0002_review_user.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
