<<<<<<< HEAD:reviews/migrations/0003_review_user.py
# Generated by Django 3.2.6 on 2021-08-14 07:29
=======
# Generated by Django 3.2.6 on 2021-08-14 06:44
>>>>>>> efe93704a40d3d3419007dc32c824c1b5b2e1fc1:reviews/migrations/0002_review_user.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:reviews/migrations/0003_review_user.py
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_review_target'),
=======
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> efe93704a40d3d3419007dc32c824c1b5b2e1fc1:reviews/migrations/0002_review_user.py
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
