# Generated by Django 3.2.6 on 2021-08-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['updated_at']},
        ),
    ]
