# Generated by Django 3.2.6 on 2021-08-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-updated_at']},
        ),
    ]
