<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-16 11:38
=======
# Generated by Django 3.2.6 on 2021-08-15 15:27
>>>>>>> service_list
=======
# Generated by Django 3.2.6 on 2021-08-16 10:53
>>>>>>> userlogin

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> userlogin
        ('community', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> service_list
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(15)], verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('reply', models.IntegerField(default=0, verbose_name='답글위치')),
<<<<<<< HEAD
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='community.board', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
<<<<<<< HEAD
=======
>>>>>>> service_list
=======
>>>>>>> userlogin
            ],
            options={
                'verbose_name': '자유게시판 댓글',
                'verbose_name_plural': '자유게시판 댓글',
                'db_table': '자유게시판 댓글',
            },
        ),
    ]
