<<<<<<< Updated upstream
# Generated by Django 3.2.6 on 2021-08-20 13:41
=======
# Generated by Django 3.2.6 on 2021-08-20 13:31
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ('community', '0001_initial'),
        ('comment', '0001_initial'),
=======
        ('comment', '0001_initial'),
        ('community', '0001_initial'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='community.board', verbose_name='게시글'),
        ),
    ]
