<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-12 11:22
=======
# Generated by Django 3.2.6 on 2021-08-12 01:49
>>>>>>> 2f0b80a5dd0c5ecd966b3f3ae09e3f0752a79281

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
