<<<<<<< HEAD:comment/migrations/0003_comment_user.py
# Generated by Django 3.2.6 on 2021-08-14 07:29
=======
# Generated by Django 3.2.6 on 2021-08-14 06:44
>>>>>>> efe93704a40d3d3419007dc32c824c1b5b2e1fc1:comment/migrations/0002_comment_user.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0002_comment_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
